# Generated by Django 3.2.6 on 2021-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_auto_20210831_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='source',
            field=models.CharField(default='', max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Автор'),
        ),
    ]
