# Generated by Django 4.0.1 on 2022-01-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('prise', models.IntegerField(verbose_name='Цена')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('content', models.TextField(verbose_name='Текст объявления')),
                ('property_type', models.CharField(max_length=20, verbose_name='Вид недвижимости')),
                ('type_transaction', models.CharField(blank=True, max_length=20, verbose_name='Вид сделки')),
                ('town', models.CharField(max_length=30, verbose_name='Город')),
                ('district', models.CharField(max_length=150, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=20, verbose_name='Улица')),
                ('building_number', models.CharField(blank=True, max_length=15, verbose_name='Номер дома')),
                ('name_seller', models.CharField(max_length=30, verbose_name='Имя')),
                ('number_rooms', models.CharField(blank=True, max_length=15, verbose_name='Количество комнат')),
                ('square_living', models.CharField(blank=True, max_length=15, verbose_name='Площадь помещения')),
                ('land_area', models.CharField(blank=True, max_length=10, verbose_name='Площадь земли')),
                ('purpose_of_the_land', models.CharField(blank=True, max_length=30, verbose_name='Назначение земли')),
                ('number_floors', models.CharField(blank=True, max_length=15, verbose_name='Этаж для картиры (этажей для дома)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo1', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 1', width_field='image_width')),
                ('photo2', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 2', width_field='image_width')),
                ('photo3', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 3', width_field='image_width')),
                ('photo4', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 4', width_field='image_width')),
                ('photo5', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 5', width_field='image_width')),
                ('photo6', models.ImageField(blank=True, height_field='image_height', upload_to='photo_adv/%Y/%m/%d', verbose_name='Фото 6', width_field='image_width')),
                ('login', models.CharField(blank=True, max_length=30, verbose_name='Логин')),
                ('image_width', models.IntegerField(default=360)),
                ('image_height', models.IntegerField(default=200)),
                ('art', models.CharField(blank=True, max_length=20, verbose_name='Артикул')),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('last_num_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Фото цифры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adv.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
