# Generated by Django 3.2.6 on 2021-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Право', 'verbose_name_plural': 'Право'},
        ),
        migrations.AlterField(
            model_name='law',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='law',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='law',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликоывано'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
