# Generated by Django 3.2.6 on 2021-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_auto_20210830_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='source',
            field=models.CharField(default='', max_length=150, verbose_name='Ресурс автора'),
        ),
    ]
