# Generated by Django 3.2.6 on 2021-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('type', models.CharField(max_length=200, verbose_name='Тип сообщения')),
                ('art', models.CharField(max_length=200, verbose_name='Артикул')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
            ],
        ),
    ]
